### ISSUE TITLE
ECI's Polling Stations locations website doesn't allow to copy and distribute

### ISSUE THREAD

**Issue by SrihariThalla** [datameet/maps#13]
Hi,
Thanks for your effort and the amazing work!

I have been thru the DataMeet Google Groups thread ([link](https://groups.google.com/d/msg/datameet/fBwoZqi-lvw/t-3-e1fhf0MJ)) and it seems [ECI's Polling Station Locations](http://psleci.nic.in/) website doesn't allow to copy and distribute data on that website!

> Disclaimer : You may not use this website or the information on it for commercial purposes. You may not copy or distribute any information that you get from this website.

Did DataMeet obtain permission/license from ECI regarding the same? Can you point me to it?

DataMeet's [India - District Boundaries](http://projects.datameet.org/maps/districts/) states, along with #6:

> The District Boundaries of India, Scraped from ECI's Poling Station Locations Website.

Thanks!

**Comment by SrihariThalla** [comment]
I just stumbled upon this thread in DataMeet Google Groups - [Government Open Data Licence – India (GODL) has been gazette notified on February 13, 2017](https://groups.google.com/forum/#!topic/datameet/B9vr5dbUSaA).

Does it allow the ECI's data to be in the open?

**Comment by devdattaT** [comment]
I'm not a lawyer, but you should note that when we scraped the data, at that time this notice was not present.

**Comment by SrihariThalla** [comment]
Thanks for the info!
