### ISSUE TITLE
The boundary lines seem to be a little off.

### ISSUE THREAD

**Issue by sudbasnet** [datameet/maps#15]
Hi folks, you guys have done a great job with the maps but the boundary lines do not seem to match when put them on top of google maps. All the administrative boundaries seem to be a little off. The district boundaries might have changed but they should at least line up with the state boundaries on google. And I have compared the dist_2011 maps with other maps available online (not 2011 maps) like the GADM and maps available on IPUMS International website, they seem to be more accurate for whichever year they are mapped for.
Could you let me know the methods used to create this map.

**Comment by devdattaT** [comment]
Most of these files were created by scraping some Government sites. Do note that these should not be used for maps at a scale finer than say 1:1,00,000. If you want precise boundaries, then only the Survey of India is the Authoritative source for that. You can buy vector data from them directly.

**Comment by sudbasnet** [comment]
Thank you for the response.
