### ISSUE TITLE
Where can I get pre-delimitation Shapefiles for Assembly Constituencies ? 

### ISSUE THREAD

**Issue by panuganti** [datameet/maps#16]
Where can I get pre-delimitation Shapefiles for Assembly Constituencies ? Thanks.

**Comment by eeemda** [comment]
Sandip Sukhtankar put this together [this](http://faculty.virginia.edu/sandip/data.html#maps) in the ultimate public good.

[MLInfo Map](https://www.mlinfomap.com/) also has them, but they're very expensive.

**Comment by devdattaT** [comment]
This data is also present at: https://groups.google.com/d/msg/datameet/tYMSW1sbjwg/alfUTFpSDwAJ
