### ISSUE TITLE
Projection for ECI assembly constituency datasets

### ISSUE THREAD

**Issue by planemad** [datameet/maps#23]
What is the projection for the ECI AC data https://github.com/datameet/maps/tree/master/eci/AC_Data/States? `EPSG:4326` places the data near the equator.

cc @thejeshgn @devdattaT

**Comment by devdattaT** [comment]
This data is not properly georeferenced. I think if you open it in some GIS software, many states overlap.

This is how it was present on the ECI site about 10 years ago.

**Comment by devdattaT** [comment]
Also these are pre-delimitation boundaries.

**Comment by planemad** [comment]
Aha, so this is more updated https://github.com/datameet/maps/tree/master/assembly-constituencies ?

**Comment by devdattaT** [comment]
Yes, that is the latest one.
