### ISSUE TITLE
Layer not valid

### ISSUE THREAD

**Issue by zachokeeffe** [datameet/maps#27]
Neither QGis nor R can open the shapefile.

**Comment by devdattaT** [comment]
@zachokeeffe Which one?

**Comment by zachokeeffe** [comment]
https://github.com/datameet/maps/tree/master/Districts/Census_2001

**Comment by devdattaT** [comment]
It's working for me; I've Tried on 2 different systems.

**Comment by zachokeeffe** [comment]
Never mind, I messed up the download, sorry.

**Comment by zachokeeffe** [comment]
Sorry, it works. That's my bad. I messed up the download.
