### ISSUE TITLE
Can these maps be used in research works.

### ISSUE THREAD

**Issue by bedantaguru** [datameet/maps#31]
Given the fact stated in Geospatial Information Regulation Bill 2016, can I use state and country boundary maps in research works..

**Comment by devdattaT** [comment]
This data can be used as it's been released under a  Creative Commons Attribution-ShareAlike 2.5 India license.

The 'Geospatial Information Regulation Bill 2016' was only a draft, and never actually became a law, so it is not really relevant to your usage. According to the current laws, if you 'publish' a map, you need to get it verified by the Survey of India, and in that case the source of the data has no bearing. See this [discussion ](https://groups.google.com/d/msg/datameet/KTfbPWhBjv8/eX5uihWKAwAJ)for more details.
