### ISSUE TITLE
Add official country and state boundaries of India from Survey of India

### ISSUE THREAD

**Issue by planemad** [datameet/maps#32]
The Survey of India has made the shapefiles of the official borders available on their online portal https://indiamaps.gov.in/soiapp/

Shapefiles:
https://indiamaps.gov.in/SOIApp/downloadLayer/IndiaBoundary.zip
https://indiamaps.gov.in/SOIApp/downloadLayer/StateBoundary.zip

Visually checked them and they look quite accurate except for some issues along the coastline. This can be used to replace some of the existing shapefiles in the repository.

**Comment by devdattaT** [comment]
Thanks @planemad This dataset looks great in places, but at others, is extremly weird, and in some places wrong.

Some Examples (Blue with Black boundaries is existing State Boundary; Red is the SOI boundary)  :
Gulf of Kutch & Kabhat:

![gujrat](https://user-images.githubusercontent.com/4159622/47016368-1c39f180-d16d-11e8-8a1f-c81d72aff2db.jpeg)


Pondicherry Boundary:

![pondy](https://user-images.githubusercontent.com/4159622/47016399-3c69b080-d16d-11e8-98f3-d02bef401614.jpeg)

Even the New AP/Telengana boundry does not match the one that they have at http://www.surveyofindia.gov.in/files/Telangana%20Map.pdf

**Comment by planemad** [comment]
You are right, the State boundaries might need some cleanup before use. Also found holes in Madhya Pradesh and Dadra Nagar Haveli

<img width="273" alt="screen shot 2018-10-16 at 7 52 36 pm" src="https://user-images.githubusercontent.com/126868/47023375-34197180-d17d-11e8-9ad4-4a67feb4e3ce.png">
<img width="398" alt="screen shot 2018-10-16 at 7 53 15 pm" src="https://user-images.githubusercontent.com/126868/47023377-34197180-d17d-11e8-968f-eb679dfaf235.png">

The International boundary looks much better.

**Comment by thejeshgn** [comment]
It doen't mention Goverment Open Data License.


This Public Portal facilitates free access to accurate &amp; authoritative GIS-ready spatial data to empower, inform &amp; enrich every citizen<br>
			• Free use of data for Consultative, Research and Education purposes
			• Free access to various base maps viz Imagery, Hill Shade and Vector data
			• Citizens can annotate over the autorotative basemap and download the work done for their use
			• Citizens can download the approved boundary files for Consultative, Research and Education purposes


Practically all use except commercial. Should we write to them, to release under GODL?

**Comment by planemad** [comment]
> Should we write to them, to release under GODL?

@thejeshgn yes its best to clarify if this comes under NDSAP+GODL

**Comment by planemad** [comment]
Also to note that this dataset does not fall in the [negative list of products from SoI](
http://www.surveyofindia.gov.in/files/Negative%20list24.12.2014_1.doc). Does that mean it automatically comes under GODL or does that need to be explicitly stated?

cc @naveenpf

**Comment by thejeshgn** [comment]
We can write one as DataMeet community.

**Comment by thejeshgn** [comment]
Should I start a letter for coediting?

**Comment by thejeshgn** [comment]
@devdattaT @planemad @naveenpf 

Also should we add them to the under 
https://github.com/datameet/maps/tree/master/Survey-of-India-Index-Maps

As shapefiles, without changing anything.

**Comment by thejeshgn** [comment]
1. Added https://github.com/datameet/maps/tree/master/Survey-of-India-Index-Maps

2. I will write to the list

**Comment by thejeshgn** [comment]
Screenshots for the record

![soi_external_boundaries_download](https://user-images.githubusercontent.com/76114/48550230-30057e80-e8f8-11e8-9c3a-c3777af12e62.png)
![soi_external_boundaries_note](https://user-images.githubusercontent.com/76114/48550231-309e1500-e8f8-11e8-8536-6f1f67981692.png)

**Comment by planemad** [comment]
This is done!

**Comment by answerquest** [comment]
as of 2022-04-29, SOI website has shared a shapefile on https://surveyofindia.gov.in/pages/outline-maps-of-india for India International boundary vector format. It is in CRS LLC_WGS84 and isn't very accurate at higher zooms esp around islands and coastlines. But I guess that's the most "official" one available. Should that be added here for completion sake?

**Comment by planemad** [comment]
@answerquest definitely makes sense to archive a copy on the maps repo

**Comment by thejeshgn** [comment]
@devdattaT and @planemad  here it is  https://github.com/datameet/maps/pull/76 for archival purpose.
