### ISSUE TITLE
Shapefiles for Ladakh and J&K boundries

### ISSUE THREAD

**Issue by devvartpoddar** [datameet/maps#45]
Hey team,

I am working on a spatial analysis of ID in India, and have been suggested to apply the **new J&K and Ladakh boundaries** instead of keeping them together. Can you suggest how to do so using the shapefiles already present? I considered combining the geometries at a district level, but it does not have the level of detail (geometry for gilgit and other districts) that the GoI used to define the new UTs. Is there an external dataset I can use to fix this?

Thanks!
Dev

**Comment by sudevschiz** [comment]
Anybody working on this?

**Comment by haideralipunjabi** [comment]
I also needed this for a Covid-19 Tracker website, but since it wasn't available, I used an SVG I made from  [Map of UTs](http://164.100.117.97/WriteReadData/userfiles/Map%20of%20UTs.pdf) , found in this [Press Release](https://pib.gov.in/PressReleasePage.aspx?PRID=1590112)

**Comment by devdattaT** [comment]
We could use: http://164.100.117.97/WriteReadData/userfiles/India%20-%20Political1.pdf for the New UT Boundaries

**Comment by vijaybarve** [comment]
Do we have the revised shape files ready? Is anyone working on it?
