### ISSUE TITLE
Some missing shapes

### ISSUE THREAD

**Issue by masoodnaqvi1966** [datameet/maps#48]
I checked districts which are only 641 districts instead of 720 districts currently in India.
State of new Andhra Pradesh and Telengana is also missing
UTs J&K and Ladakh is also mission

**Comment by devdattaT** [comment]
The States have been updated.

The districts are as per the 2011 census.

If you need updated Districts, you could look at other sources, such as: https://github.com/justinelliotmeyers/India_Official_Boundaries_2019
