### ISSUE TITLE
License data with `CC-by 4.0` to be compatible with Government Open Data License

### ISSUE THREAD

**Issue by planemad** [datameet/maps#56]
Most datasets in this repo is [`CC-by-sa 2.5`](https://creativecommons.org/about/cclicenses/) which makes it hard to practically use since it forces downstream use to be relicensed. Further, [CC licenses include scope for data only from v4.0](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-databases). 

Proposing that we drop the share alike clause and adopt **CC-by 4.0**.

The primary goal of this would be to ensure DataMeet datasets can be mixed with the following datasets without additional restrictions:
- Data with [India-Government Open Data License](https://data.gov.in/government-open-data-license-india) . This would maximize data reuse and visibility of DataMeet.
- Data with ODbL License including the [OpenStreetMap Project](https://wiki.osmfoundation.org/wiki/Licence/Licence_Compatibility#Licences_that_require_downstream_attribution)

**Why drop the share alike clause?**

The share alike condition requires CC-by-sa data sets mixed with more open GODL licensed datasets to become CC-by-SA. Thus using datameet data results in more restrictive data. To maximize interoperability, we should drop this restriction http://opendatahandbook.org/guide/en/what-is-open-data/

Most open data portals including data.gov.in have only a `-by` attribution requirement and does not force relicensing https://wiki.creativecommons.org/wiki/Data_and_CC_licenses

## Open questions

- Any reservations against dropping the share alike requirement going forward for new datasets?
- If adopting a new license, should it be **CC-by** or a more database appropriate **ODC-by** https://help.data.world/hc/en-us/articles/115006114287-Common-license-types-for-datasets?
- Should we also relicense existing data? What would be the process for that?

Tagging all repo contributors for approval: 
- [x] @thejeshgn 
- [x] @devdattaT 
- [x] @planemad
- [x] @geohacker 
- [x] @katehara 
- [x] @sanand0

**Comment by devdattaT** [comment]
I don't see any issue with moving to a better license. Practically speaking, in India no one really follows any license, and I have seen this data been used in all kinds of places, with neither attribution, nor sharing of derivative works.

**Comment by planemad** [comment]
Of course the really open way would be a CC-0/Public domain. Thats an option if others are in favor of it. Personally, i think attribution is a fair basic requirement to enforce and is on par with most open datasets.

**Comment by thejeshgn** [comment]
I am okay with the change.

**Comment by geohacker** [comment]
I agree with dropping share-alike and move to cc-by 4.0

**Comment by sanand0** [comment]
I'm OK with the change

**Comment by gnowgi** [comment]
When a sharing practice yields to less sharing practice, it is not good news for those who like to sustain sharing. A license that was initially devised to promote more and more sharing will be considered as a restriction by only those who do not want to encourage data sharing in all situations. Yes, the copyleft clause does restrict, but restrict precisely those practices that have the intent to stop sharing.

**Comment by planemad** [comment]
☝️ Crosslinking to deeper discussion on share alike licenses https://metastudio.org/t/map-data-sets-as-cc-4-0/5410/1
