### ISSUE TITLE
Add repo LICENSE.md

### ISSUE THREAD

**Issue by planemad** [datameet/maps#57]
In addition to licensing the data https://github.com/datameet/maps/issues/56, we should add a repository LICENSE.md for the code that is mostly applicable to the website content and any processing scripts in future if any

Proposing that we adopt a simple MIT license, unless there are other opinions.

**Approval**

- [x] @katehara 
- [x] @thejeshgn

**Comment by thejeshgn** [comment]
+1

**Comment by planemad** [comment]
Capturing ✅ from @katehara 

![Screen Shot 2020-12-02 at 3 10 16 PM](https://user-images.githubusercontent.com/126868/100925828-8b3f4500-34b0-11eb-82a0-d93a0cde7f93.png)
