### ISSUE TITLE
Extension request - Pre-2008 Constituencies?

### ISSUE THREAD

**Issue by DavidSorge** [datameet/maps#66]
Thank you all for this amazing project! Truly this is remarkable!

I don't know if this is possible, but it would be enormously useful for researchers looking at longer-term political trends if we could put together maps of the Pre-2008 Parliamentary and Assembly Constituencies. as laid out by the Delimitation Commission of 1973. I'm not even sure where to start with this, and I'm sure it would be a huge undertaking, but if it could be done, it would extend the metaphorical horizon for analysis of voting patterns all the way back to the Emergency.

Is this a possible future extension of this work?

**Comment by DavidSorge** [comment]
PS, I should say that there are non-FOSS resources available for this, so it is possible in principle, but of course the licensing fees for these non-FOSS maps are quite costly.

**Comment by devdattaT** [comment]
You will find them here: https://groups.google.com/g/datameet/c/tYMSW1sbjwg/m/alfUTFpSDwAJ

**Comment by DavidSorge** [comment]
This is amazing! Thank you so much! I didn't know this existed!

**Comment by DavidSorge** [comment]
If I were to work on these further, would it be helpful/permissible for me to put in a pull request with this data? I wasn't able to figure out what the licensing looks like, and I want to be careful not to cause any problems.
