### ISSUE TITLE
State level borders with Ladakh

### ISSUE THREAD

**Issue by vijaybarve** [datameet/maps#67]
Looking for a India State boundary with Ladakh and Jammu and Kashmir UTs marked. I need a shape file. Any pointers? Is anyone working on digitizing?

**Comment by devdattaT** [comment]
Have you looked at the data in : https://github.com/datameet/maps/tree/master/States?

**Comment by vijaybarve** [comment]
Thanks @devdattaT I was mislead due to Quick View on this page http://projects.datameet.org/maps/states/
