### ISSUE TITLE
Create a Shape file 

### ISSUE THREAD

**Issue by BikramSR04** [datameet/maps#81]
I currently have two files in hand. One file is a Shapefile for the state level, and the second one contains zone-wise state tags. For example, one zone might include three or four state names. My requirement is to create a Shapefile according to zones. For instance, Zone One might include West Bengal, Bihar, and Jharkhand, while Zone Two might include Bihar, Uttar Pradesh, and Uttarakhand. The task is to convert the state-level Shapefile into zone-level boundaries and map them accordingly. One more thing all this working done in Google Colab Python platfrom.

**Comment by devdattaT** [comment]
@BikramSR04 This would not be the right place to ask for help with working with shapefiles. You can ask on a forum such as gis.stackexchange.com or any other GIS forum.
